### PR TITLE
Support clearing fields

### PR DESCRIPTION
**Pull request by danielmarbach**
Addressed https://github.com/leonsteinhaeuser/project-beta-automations/issues/69

### CODE REVIEW

**Review by leonsteinhaeuser — APPROVED** [review]
LGTM

Have you already tested this?

**Comment by danielmarbach** [comment]
I didn't have time before my vacation. I'm mostly offline until beginning of August

**Comment by leonsteinhaeuser** [comment]
No problem. Enjoy your vacation. I will take responsibility for the tests.

**Comment by leonsteinhaeuser** [comment]
@danielmarbach I am sorry it has taken so long. I have been very busy the last few months. I finally had some time to test this and unfortunately the test with the "Date" field does not work as expected.

See (test_user.sh):

```txt
"Date": PVTF_lAHOAoeKQc2PEc4ADXso
Updating date field: "Date" with value: null
{errors:[{extensions:{value:null,problems:[{path:[],explanation:Could not coerce value 
ull\ to Date}]},locations:[{line:6,column:9}],message:Variable $fieldValue of type Date! was provided invalid value}]}
```

**Comment by danielmarbach** [comment]
It sounds like it doesn't execute the clear but tries to assign null to the field value. I'm a but removed from this but I can try this give it another look at some point

**Comment by goldiegadde** [comment]
Is anyone still workign on this, a very useful feature to have

**Comment by danielmarbach** [comment]
Sorry no. Feel free to take it from here

**Pull request closed without merging**
