### PR TITLE
Add GH App Auth support

### PR DESCRIPTION
**Pull request by MatteoManzoni**
This PR introduces the support for GH App Auth in the action. 
With the support to GH App Auth this action should be able to require less privileges than `org:admin` which, in many cases, is deemed too broad to be used.

The input requirements of the modified action to use GH App Auth are:
- gh_app_secret_key: the RSA secret key generated during the App creation process used to sign App JWT tokens
- gh_app_ID: GH App ID
- gh_app_installation_ID: Installation ID of the App on your org

### CODE REVIEW

**Comment by leonsteinhaeuser** [comment]
@MatteoManzoni thank you very much for providing this solution. I would like to ask you to write a few sentences in the README.md so that others can understand what they need to do to use this feature.

**Comment by MatteoManzoni** [comment]
Sure @leonsteinhaeuser, I've totally forgot. I'll add documentation for the  new variables and a new paragraph with GH App specific instructions, soon.

**Comment by MatteoManzoni** [comment]
Hey @leonsteinhaeuser, I've update the README, let me know if you have any feedback

**Comment by leonsteinhaeuser** [comment]
First of all great work.

When I added this function to the release-v1.2.0 branch and created a pre-release version from it, I found in my testing that the action.yml file pointed to the wrong script. 

```txt
 /home/runner/work/_temp/f4f8965b-ec35-40a2-ae04-ecd5ab7ed8e3.sh: line 27: /home/runner/work/_actions/leonsteinhaeuser/project-beta-automations/v1.2.0-alpha.1/ghapp_credential_helper.sh: No such file or directory
could not prompt: EOF
25l? How would you like to authenticate GitHub CLI?  [Use arrows to move, type to filter]
> Login with a web browser
  Paste an authentication token
25h
```

Since it was just a typo, I fixed it so we can release this feature soon.

**Comment by MatteoManzoni** [comment]
> @MatteoManzoni first of all great work.
> 
> When I added this function to the release-v1.2.0 branch and created a pre-release version from it, I found in my testing that the action.yml file pointed to the wrong script.
> 
> ```
>  /home/runner/work/_temp/f4f8965b-ec35-40a2-ae04-ecd5ab7ed8e3.sh: line 27: /home/runner/work/_actions/leonsteinhaeuser/project-beta-automations/v1.2.0-alpha.1/ghapp_credential_helper.sh: No such file or directory
> could not prompt: EOF
> 25l? How would you like to authenticate GitHub CLI?  [Use arrows to move, type to filter]
> > Login with a web browser
>   Paste an authentication token
> 25h
> ```
> 
> Since it was just a typo, I fixed it so we can release this feature soon.

@leonsteinhaeuser thank you so much, that was definitely a typo

**Comment by leonsteinhaeuser** [comment]
@MatteoManzoni this feature is now available with version v1.2.0

**Comment by MatteoManzoni** [comment]
Thank you so much @leonsteinhaeuser

**Pull request merged**
